In [ ]:
# After installetion of numpy, kernel should be restart
!pip install numpy

In [1]:
import numpy as np

## Array

In [2]:
arr = np.array([1, 2, 3, 4, 5])

In [3]:
arr

array([1, 2, 3, 4, 5])

In [4]:
arr = np.array([1, 2.2, "3"])
arr

array(['1', '2.2', '3'], dtype='<U32')

In [6]:
arr = np.array([1, 2.2])

In [7]:
arr

array([1. , 2.2])

In [8]:
arr = np.array([1, 2, 3, 4, 5])

In [9]:
arr

array([1, 2, 3, 4, 5])

In [12]:
arr = np.array([1, 2, 3, 4, 5], dtype=int)
arr

array([1, 2, 3, 4, 5])

In [15]:
arr = np.array([1, 2, 3, 4, 5], dtype=int, ndmin=10)
arr

array([[[[[[[[[[1, 2, 3, 4, 5]]]]]]]]]])

In [16]:
arr.ndim

10

In [17]:
l = [10, 20, 30, 40, 50]
arr = np.array(l)
arr

array([10, 20, 30, 40, 50])

In [18]:
t = (10, 20, 30, 40, 50)
arr = np.array(t)
arr

array([10, 20, 30, 40, 50])

In [19]:
arr = np.asarray(l)
arr

array([10, 20, 30, 40, 50])

In [20]:
arr.cumsum()

array([ 10,  30,  60, 100, 150], dtype=int32)

In [21]:
arr.argmax()

4

In [22]:
arr.argmin()

0

In [23]:
arr.dtype

dtype('int32')

In [25]:
arr = np.arange(0, 100, 2)
arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32,
       34, 36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62, 64, 66,
       68, 70, 72, 74, 76, 78, 80, 82, 84, 86, 88, 90, 92, 94, 96, 98])

In [26]:
arr = np.arange(0, 100, 1)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [27]:
arr.reshape(10, 10)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [28]:
arr.reshape(9, 10)

ValueError: cannot reshape array of size 100 into shape (9,10)

In [29]:
arr.reshape(20, 5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44],
       [45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54],
       [55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64],
       [65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74],
       [75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84],
       [85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94],
       [95, 96, 97, 98, 99]])

In [30]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [31]:
arr.resize(10, 10)

In [32]:
arr

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

## From Function

In [37]:
np.fromfunction(lambda x, y: x*y, (4, 4))

array([[0., 0., 0., 0.],
       [0., 1., 2., 3.],
       [0., 2., 4., 6.],
       [0., 3., 6., 9.]])

In [38]:
np.fromfunction(lambda x, y: x==y, (4, 4))

array([[ True, False, False, False],
       [False,  True, False, False],
       [False, False,  True, False],
       [False, False, False,  True]])

In [39]:
np.fromfunction(lambda x, y: x!=y, (4, 4))

array([[False,  True,  True,  True],
       [ True, False,  True,  True],
       [ True,  True, False,  True],
       [ True,  True,  True, False]])

In [40]:
np.fromfunction(lambda x, y: x<y, (4, 4))

array([[False,  True,  True,  True],
       [False, False,  True,  True],
       [False, False, False,  True],
       [False, False, False, False]])

In [41]:
l

[10, 20, 30, 40, 50]

In [42]:
for i in l:
    print(i)

10
20
30
40
50


In [43]:
np.fromiter(l, int)

array([10, 20, 30, 40, 50])

In [44]:
np.fromiter(l, float)

array([10., 20., 30., 40., 50.])

In [46]:
np.fromstring("10,30,50,384,28,46", sep=",", dtype=int)

array([ 10,  30,  50, 384,  28,  46])

In [48]:
np.fromstring("10 30 50 384 28 46", sep=" ", dtype=int)

array([ 10,  30,  50, 384,  28,  46])

In [52]:
np.fromstring("1.2.3.4.5.6.7.8.9", sep=".", dtype=int)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

## Zeros and Ones

In [54]:
arr = np.zeros(100, dtype=int)
arr

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [55]:
arr.resize(10, 10)

In [56]:
arr

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [58]:
arr[2:5, 2:5]

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [61]:
arr[2:5, 2:5] = 255

In [62]:
arr

array([[  0,   0,   0,   0,   0,   0,   0,   0,   0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0],
       [  0,   0, 255, 255, 255,   0,   0,   0,   0,   0],
       [  0,   0, 255, 255, 255,   0,   0,   0,   0,   0],
       [  0,   0, 255, 255, 255,   0,   0,   0,   0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0]])

In [63]:
ones = np.ones(100, dtype=int)
ones

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [64]:
ones.resize(10, 10)

In [65]:
ones

array([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1]])

In [66]:
ones[2:5, 2:5]

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [68]:
ones[2:5, 2:5] = [[20, 18, 328], [36, 871, 35], [28, 42, 90]]

In [69]:
ones

array([[  1,   1,   1,   1,   1,   1,   1,   1,   1,   1],
       [  1,   1,   1,   1,   1,   1,   1,   1,   1,   1],
       [  1,   1,  20,  18, 328,   1,   1,   1,   1,   1],
       [  1,   1,  36, 871,  35,   1,   1,   1,   1,   1],
       [  1,   1,  28,  42,  90,   1,   1,   1,   1,   1],
       [  1,   1,   1,   1,   1,   1,   1,   1,   1,   1],
       [  1,   1,   1,   1,   1,   1,   1,   1,   1,   1],
       [  1,   1,   1,   1,   1,   1,   1,   1,   1,   1],
       [  1,   1,   1,   1,   1,   1,   1,   1,   1,   1],
       [  1,   1,   1,   1,   1,   1,   1,   1,   1,   1]])

In [70]:
ones+5

array([[  6,   6,   6,   6,   6,   6,   6,   6,   6,   6],
       [  6,   6,   6,   6,   6,   6,   6,   6,   6,   6],
       [  6,   6,  25,  23, 333,   6,   6,   6,   6,   6],
       [  6,   6,  41, 876,  40,   6,   6,   6,   6,   6],
       [  6,   6,  33,  47,  95,   6,   6,   6,   6,   6],
       [  6,   6,   6,   6,   6,   6,   6,   6,   6,   6],
       [  6,   6,   6,   6,   6,   6,   6,   6,   6,   6],
       [  6,   6,   6,   6,   6,   6,   6,   6,   6,   6],
       [  6,   6,   6,   6,   6,   6,   6,   6,   6,   6],
       [  6,   6,   6,   6,   6,   6,   6,   6,   6,   6]])

In [83]:
mul_ones = np.ones((4, 5, 5), dtype=int)

In [84]:
mul_ones

array([[[1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]],

       [[1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]],

       [[1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]],

       [[1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]]])

## Random

In [90]:
from numpy.random import rand, randn, randint

In [94]:
rand(3, 3)

array([[0.74840704, 0.0609214 , 0.35485211],
       [0.00128585, 0.63451841, 0.59704421],
       [0.40762538, 0.84370924, 0.24655147]])

In [96]:
randn(4, 4)

array([[ 0.37420853,  1.10625318, -0.09318075, -0.95644043],
       [ 0.9516582 ,  1.64808529, -1.00262214, -0.25679686],
       [ 0.65469657, -0.41565511,  0.86300206,  0.810616  ],
       [ 0.44873363, -0.25524633, -0.38912489, -0.13664722]])

In [109]:
randint(10, 20, (5, 5))

array([[13, 19, 15, 17, 12],
       [14, 16, 11, 16, 12],
       [14, 13, 14, 14, 10],
       [19, 16, 10, 15, 17],
       [12, 14, 19, 12, 13]])

## Stats and maths

In [114]:
arr = randint(10, 100, (5, 5))

In [115]:
arr

array([[39, 60, 53, 90, 92],
       [40, 92, 79, 89, 82],
       [89, 21, 27, 59, 12],
       [99, 61, 13, 59, 23],
       [48, 56, 87, 69, 41]])

In [116]:
np.sin(arr)

array([[ 0.96379539, -0.30481062,  0.39592515,  0.89399666, -0.77946607],
       [ 0.74511316, -0.77946607, -0.44411267,  0.86006941,  0.31322878],
       [ 0.86006941,  0.83665564,  0.95637593,  0.63673801, -0.53657292],
       [-0.99920683, -0.96611777,  0.42016704,  0.63673801, -0.8462204 ],
       [-0.76825466, -0.521551  , -0.82181784, -0.11478481, -0.15862267]])

In [117]:
np.cos(arr)

array([[ 0.26664293, -0.95241298, -0.91828279, -0.44807362, -0.62644445],
       [-0.66693806, -0.62644445, -0.89597095,  0.51017704,  0.9496777 ],
       [ 0.51017704, -0.54772926, -0.29213881, -0.77108022,  0.84385396],
       [ 0.03982088, -0.25810164,  0.90744678, -0.77108022, -0.53283302],
       [-0.64014434,  0.85322011,  0.56975033,  0.99339038, -0.98733928]])

In [118]:
np.tan(arr)

array([[  3.61455441,   0.32004039,  -0.4311582 ,  -1.99520041,
          1.24427006],
       [ -1.11721493,   1.24427006,   0.49567753,   1.68582537,
          0.32982641],
       [  1.68582537,  -1.52749853,  -3.2737038 ,  -0.82577401,
         -0.63585993],
       [-25.09253498,   3.74316794,   0.46302113,  -0.82577401,
          1.58815308],
       [  1.20012724,  -0.61127369,  -1.44241747,  -0.11554855,
          0.1606567 ]])

In [119]:
np.pi

3.141592653589793

In [120]:
np.degrees(arr)

array([[2234.53540101, 3437.74677078, 3036.67631419, 5156.62015618,
        5271.2117152 ],
       [2291.83118052, 5271.2117152 , 4526.36658153, 5099.32437666,
        4698.25392007],
       [5099.32437666, 1203.21136977, 1546.98604685, 3380.45099127,
         687.54935416],
       [5672.2821718 , 3495.0425503 ,  744.84513367, 3380.45099127,
        1317.8029288 ],
       [2750.19741663, 3208.56365273, 4984.73281764, 3953.4087864 ,
        2349.12696004]])

In [121]:
arr

array([[39, 60, 53, 90, 92],
       [40, 92, 79, 89, 82],
       [89, 21, 27, 59, 12],
       [99, 61, 13, 59, 23],
       [48, 56, 87, 69, 41]])

In [122]:
np.min(arr)

12

In [124]:
np.max(arr)

99

In [131]:
np.percentile(arr, 50, axis=1)

array([60., 82., 27., 59., 56.])

In [126]:
arr[0]

array([39, 60, 53, 90, 92])

In [132]:
np.median(arr[1])

82.0

In [133]:
np.mean(arr[1])

76.4

In [134]:
np.sort(arr)

array([[39, 53, 60, 90, 92],
       [40, 79, 82, 89, 92],
       [12, 21, 27, 59, 89],
       [13, 23, 59, 61, 99],
       [41, 48, 56, 69, 87]])

In [135]:
np.std(arr)

26.605262637305426

In [136]:
np.var(arr)

707.8400000000001

In [137]:
np.sqrt(np.var(arr))

26.605262637305426